"""
PDF export service for lesson plans.
Generates professional PDF documents from lesson plan data.
"""

import os
from typing import Dict, List, Optional
from datetime import datetime
try:
    from weasyprint import HTML, CSS
    from weasyprint.text.fonts import FontConfiguration
    WEASYPRINT_AVAILABLE = True
except ImportError:
    WEASYPRINT_AVAILABLE = False
    # Mock classes for when weasyprint is not available
    class HTML:
        def __init__(self, string):
            self.string = string
        def write_pdf(self, **kwargs):
            return b"PDF generation not available - weasyprint not installed"
    
    class CSS:
        def __init__(self, string, font_config=None):
            self.string = string
    
    class FontConfiguration:
        pass
from models import LessonPlan, LessonSection, ResourceLink

class PDFService:
    """Service for generating PDF exports of lesson plans."""
    
    def __init__(self):
        self.font_config = FontConfiguration()
        self.css_styles = self._get_css_styles()
    
    def generate_lesson_plan_pdf(self, lesson_plan: LessonPlan, sections: List[LessonSection], resources: List[ResourceLink]) -> bytes:
        """
        Generate a PDF document from lesson plan data.
        
        Args:
            lesson_plan: The lesson plan object
            sections: List of lesson sections
            resources: List of resource links
            
        Returns:
            PDF content as bytes
        """
        html_content = self._generate_html_content(lesson_plan, sections, resources)
        
        # Create PDF from HTML
        html = HTML(string=html_content)
        css = CSS(string=self.css_styles, font_config=self.font_config)
        
        pdf_bytes = html.write_pdf(stylesheets=[css], font_config=self.font_config)
        return pdf_bytes
    
    def _generate_html_content(self, lesson_plan: LessonPlan, sections: List[LessonSection], resources: List[ResourceLink]) -> str:
        """Generate HTML content for the lesson plan."""
        
        sections_html = ""
        for section in sections:
            sections_html += f"""
            <div class="section">
                <h3>{section.section_title}</h3>
                <div class="content">{section.content_text}</div>
                {f'<div class="media"><strong>Media:</strong> <a href="{section.media_link}">{section.media_link}</a></div>' if section.media_link else ''}
            </div>
            """
        
        resources_html = ""
        if resources:
            resources_html = "<h3>Resources</h3><ul>"
            for resource in resources:
                resources_html += f'<li><a href="{resource.link_url}">{resource.description or resource.link_url}</a> ({resource.type.value})</li>'
            resources_html += "</ul>"
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{lesson_plan.title}</title>
        </head>
        <body>
            <div class="header">
                <h1>{lesson_plan.title}</h1>
                <div class="metadata">
                    <p><strong>Subject:</strong> {lesson_plan.subject}</p>
                    <p><strong>Grade Level:</strong> {lesson_plan.grade_level}</p>
                    <p><strong>Duration:</strong> {lesson_plan.duration_minutes} minutes</p>
                    <p><strong>Created:</strong> {lesson_plan.created_at.strftime('%B %d, %Y')}</p>
                </div>
            </div>
            
            <div class="context">
                <h3>Context</h3>
                <p>{lesson_plan.context_description or 'No context provided'}</p>
            </div>
            
            <div class="sections">
                <h2>Lesson Sections</h2>
                {sections_html}
            </div>
            
            {resources_html}
            
            <div class="footer">
                <p>Generated by Awade - AI-powered educator support platform</p>
                <p>Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
            </div>
        </body>
        </html>
        """
        
        return html_content
    
    def _get_css_styles(self) -> str:
        """Get CSS styles for the PDF."""
        return """
        @page {
            size: A4;
            margin: 2cm;
            @top-center {
                content: "Awade Lesson Plan";
                font-size: 10pt;
                color: #666;
            }
            @bottom-center {
                content: "Page " counter(page) " of " counter(pages);
                font-size: 10pt;
                color: #666;
            }
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
        }
        
        .header {
            border-bottom: 3px solid #2c5aa0;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        .header h1 {
            color: #2c5aa0;
            margin: 0 0 15px 0;
            font-size: 28pt;
        }
        
        .metadata {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            font-size: 12pt;
        }
        
        .metadata p {
            margin: 5px 0;
        }
        
        .context {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        
        .context h3 {
            color: #2c5aa0;
            margin-top: 0;
        }
        
        .sections h2 {
            color: #2c5aa0;
            border-bottom: 2px solid #e9ecef;
            padding-bottom: 10px;
        }
        
        .section {
            margin-bottom: 25px;
            padding: 15px;
            border-left: 4px solid #2c5aa0;
            background-color: #f8f9fa;
        }
        
        .section h3 {
            color: #2c5aa0;
            margin-top: 0;
            font-size: 16pt;
        }
        
        .content {
            margin-bottom: 10px;
        }
        
        .media {
            font-size: 11pt;
            color: #666;
        }
        
        .media a {
            color: #2c5aa0;
            text-decoration: none;
        }
        
        ul {
            padding-left: 20px;
        }
        
        li {
            margin-bottom: 5px;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e9ecef;
            text-align: center;
            font-size: 10pt;
            color: #666;
        }
        
        h3 {
            color: #2c5aa0;
            font-size: 14pt;
        }
        """ 