# Docker Compose configuration for Awade

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: awade-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-awade}
      POSTGRES_USER: ${POSTGRES_USER:-awade_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-awade_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-awade_user} -d ${POSTGRES_DB:-awade}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Awade Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: awade-backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-awade_user}:${POSTGRES_PASSWORD:-awade_password}@postgres:5432/${POSTGRES_DB:-awade}
      - DEBUG=${DEBUG:-True}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRES_MINUTES=${JWT_EXPIRES_MINUTES:-60}
      - PASSWORD_MIN_LENGTH=${PASSWORD_MIN_LENGTH:-8}
      - PASSWORD_MAX_LENGTH=${PASSWORD_MAX_LENGTH:-128}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
    command: uvicorn apps.backend.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Development
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: awade-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    stdin_open: true
    tty: true

  # Frontend Production (commented out for development)
  # frontend-prod:
  #   build:
  #     context: ./apps/frontend
  #     dockerfile: Dockerfile
  #   container_name: awade-frontend-prod
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
  #   depends_on:
  #     - backend

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: awade-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: awade-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@awade.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: 