/**
 * ContentPreviewModal — AWD-M-145
 *
 * Scrollable overlay for previewing AI-generated content in the admin
 * moderation panel. Replaces the blocking `alert()` previously used in
 * ModerationList.tsx — `alert()` blocks the main thread, truncates long
 * content, and provides no scroll or formatting.
 *
 * OWASP LLM #2 (insecure output handling): content is rendered inside a
 * `<pre>` element (text only, no dangerouslySetInnerHTML) so AI-generated
 * output cannot inject markup or scripts.
 *
 * Pattern mirrors ConfirmRoleChangeModal and DeleteChildConfirmModal:
 * backdrop + dialog with `role="dialog"`, `aria-modal="true"`, focus trap
 * via useFocusTrap, and Escape-to-close.
 */

import React, { useRef } from 'react'
import { FiEye, FiX } from 'react-icons/fi'
import { useFocusTrap } from '../hooks/useFocusTrap'

interface ContentPreviewModalProps {
  /** The AI-generated content string to display. */
  content: string
  /** Called when the admin clicks Close or presses Escape. */
  onClose: () => void
}

const ContentPreviewModal: React.FC<ContentPreviewModalProps> = ({
  content,
  onClose,
}) => {
  const dialogRef = useRef<HTMLDivElement>(null)
  // Modal is always active while rendered; Escape closes it via onClose.
  useFocusTrap(dialogRef, true, onClose)

  return (
    <div
      ref={dialogRef}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="content-preview-modal-title"
      aria-describedby="content-preview-modal-body"
    >
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full p-6 sm:p-8 flex flex-col max-h-[80vh]">
        <div className="flex items-center justify-between gap-3 mb-4 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center flex-shrink-0">
              <FiEye className="w-5 h-5 text-indigo-600" />
            </div>
            <h2
              id="content-preview-modal-title"
              className="text-lg font-bold text-gray-900"
            >
              AI-Generated Content Preview
            </h2>
          </div>
          <button
            onClick={onClose}
            aria-label="Close preview"
            className="text-gray-400 hover:text-gray-600 transition-colors flex-shrink-0"
          >
            <FiX className="w-5 h-5" />
          </button>
        </div>

        <p className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 mb-4 flex-shrink-0">
          This content was generated by AI. Review carefully before approving or rejecting.
        </p>

        {/* pre renders as plain text — OWASP LLM #2: no dangerouslySetInnerHTML */}
        <pre
          id="content-preview-modal-body"
          className="flex-1 overflow-y-auto text-sm text-gray-800 whitespace-pre-wrap break-words bg-gray-50 rounded-lg p-4 font-sans border border-gray-200 min-h-0"
        >
          {content || 'No content available.'}
        </pre>

        <div className="mt-4 flex justify-end flex-shrink-0">
          <button
            onClick={onClose}
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 px-6 rounded-xl transition-colors"
            autoFocus
          >
            Close
          </button>
        </div>
      </div>
    </div>
  )
}

export default ContentPreviewModal
